services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_USERNAME", "-p", "$MYSQL_PASSWORD"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  webapp:
    image: jorgeramirezgayo/webapp14:latest
    restart: always
    ports:
      - "8443:8443"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - webapp-network

volumes:
  mysql_data:

networks:
  webapp-network:
    driver: bridge
